[env:esp32-c6-devkitm-1]
platform = espressif32
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI
    lvgl/lvgl

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE