[env:esp32-c6]
platform = espressif32@6.5.0
board = esp32-c6-devkitm-1
framework = arduino
monitor_speed = 115200

board_build.flash_mode = dio
board_build.partitions = huge_app.csv

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_LVGL_H_INCLUDE_SIMPLE

lib_deps =
    lvgl/lvgl@8.3.11
    lovyan03/LovyanGFX@1.1.12