[env:esp32c6]
platform = espressif32@6.5.0
board = esp32-c6-devkitm-1
framework = arduino

monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1