#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16

#define LV_MEM_SIZE (64U * 1024U)

#define LV_USE_PERF_MONITOR 1

#define LV_USE_SYSMON 1

#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_32 1
#define LV_FONT_MONTSERRAT_48 1

#endif