name: Build Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build Firmware
        run: pio run

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/esp32-c6-devkitc-1/firmware.bin